export class Sub {
    constructor(
        public subid: String,
        public groovyid: String,
        public name: String,
        public nohp: String,
        public email: String,
        public dateinst: Date,
        public timeinst: Date,
        public password: String,
        public datebirth: String,
        public packlev: String,
        public cardid: String,
        public nova: Number,
        public status: String,
        public regisby: String,
        public regisref: String,
        public billing: String,
        public history: String,
        public property: String,
        public cluster: String,
        public block: String,
        public streetname: String,
        public home: String,
    ) {  }
}
